heuser/heuser/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView, TemplateView


urlpatterns = [
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path('', RedirectView.as_view(url='songarchiv/', permanent=True)),
    path('songarchiv/', include('songarchiv.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

# Dies ist nur für die Entwicklung notwendig. In Produktion braucht es einen Eintrag in der conf Datei von nginx
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path("ckeditor5/", include('django_ckeditor_5.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

heuser/songarchiv/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'songarchiv'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/song/', views.add_song, name='add_song'),
    path('search/song/', views.search_song, name='search_song'),
    path('edit/song/<id>/', views.edit_song, name='edit_song'),
    path('song/<slug:slug>/', views.song, name='song'),
    path('del/song/<pk>', views.del_song.as_view(), name='del_song'),
    path('song_delete_done', views.song_delete_done, name='del_song_done'),
    path('autocomplete', views.autocomplete, name='autocomplete'),

    path('add/album/', views.add_album, name='add_album'),
    path('search/album/start', views.search_album_start, name='search_album_start'),
    path('search/album/', views.search_album, name='search_album'),
    path('edit/album/<id>/', views.edit_album, name='edit_album'),
    path('album/', views.album, name='album'),
    path('single/', views.single, name='single'),

    path('add/text/', views.add_text, name='add_text'),
    path('edit/text/<id>/', views.edit_text, name='edit_text'),
    path('text/<slug:slug>/', views.text, name='text'),

    path('print_text/', views.print_text, name='print_text'),
    path('print_chordpro/', views.print_chordpro, name='print_chordpro'),
    path('print_chords/', views.print_chords, name='print_chords'),
    path('print_nashville/', views.print_nashville, name='print_nashville'),

    path('videostaendchen/', views.videostaendchen, name= 'videostaendchen'),
    path('staendchenlist/', views.staendchenlist, name='staendchenlist'),

    path('cd_song_list/<id>/', views.cd_song_list, name='cd_song_list'),

    path('impressum/', views.impressum, name='impressum'),
    path('datenschutz/', views.datenschutz, name='datenschutz'),
    path('uebers_songarchiv/', views.uebers_songarchiv, name='uebers-songarchiv'),


]

heuser/songarchiv/models.py
from django.db import models
#from ckeditor.fields import RichTextField
from django_ckeditor_5.fields import CKEditor5Field
from django.urls import reverse
from django.utils.text import slugify

# diese Funktion kann ggf. weg, da sie in songs bei den snipplet eingesetzt war, aber eigentlich nicht benötigt wird
def dynamik_path(instance, filename):
    file_path = '{filename}'.format(filename=filename)
    return file_path


class Album(models.Model):

    ALBUM_SINGLE = (
        ('1', 'Album'),
        ('2', 'Single'),
        ('2', 'LDÖS'),
        ('2', 'Sonstiges'),
    )

    album_title = models.CharField(max_length=250)
    album_year = models.DateField(default='1900-01-01')
    album_cover_image = models.ImageField(upload_to='cover/', null=True, blank=True)
    album_spotify = models.CharField(max_length=500, default='')
    album_amazon_selling = models.CharField(max_length=1000, default='')
    album_single = models.CharField(max_length=20, choices=ALBUM_SINGLE, default='1')

    def __str__(self):
        return self.album_title


class Song(models.Model):
    song_title = models.CharField(max_length=250, unique=True)
    song_tag = models.CharField(max_length=500, blank=True, default="")
    slug = models.SlugField(max_length=70, null=True, blank=True)
    song_artist = models.CharField(max_length=250)
    song_music = models.CharField(max_length=250, blank=True, default='')
    song_lyrics = models.CharField(max_length=250, blank=True, default='')
    song_year = models.DateField(blank=True, default='1900-01-01')
    song_publisher = models.CharField(max_length=250, blank=True, default='')
    song_producer = models.CharField(max_length=125, blank=True, default='')
    song_spotify_iframe = models.CharField(max_length=500, blank=True, default='')
    song_spotify = models.URLField(max_length=250, blank=True, default='')
    song_amazon = models.URLField(max_length=250, blank=True, default='')
    song_itunes = models.URLField(max_length=250, blank=True, default='')
    song_snippet = models.FileField(upload_to='mp3/', max_length=100, blank=True)
    song_youtube = models.CharField(max_length=500, blank=True, default='')
    song_youtube_2 = models.CharField(max_length=500, blank=True, default='')
    song_youtube_3 = models.CharField(max_length=500, blank=True, default='')
    song_amazon_sale = models.CharField(max_length=250, blank=True, default='')
    song_background = models.TextField(blank=True, default='')
    song_activ = models.BooleanField(default=True)
    album = models.ForeignKey(Album, on_delete=models.PROTECT, blank=True, null=True)

    def __str__(self):
        return self.song_title

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            german_title = self.song_title.lower()
            german_title = (german_title.translate(str.maketrans({'ä': 'ae', 'ö': 'oe', 'ü': 'ue', 'ß': 'ss'})))
            german_title = 'bjoern-heuser-' + german_title
            self.slug = slugify(german_title)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        #return "/songarchiv/song/%s/" % self.slug
        return reverse('songarchiv:song', args=[str(self.slug)])
        #return reverse('songarchiv:song', kwargs={'id': self.id, 'slug': self.slug })


    class Meta:
        ordering = ['album__album_title']


class Song_Text(models.Model):
    text_text = CKEditor5Field('Text', config_name='extends')
    slug = models.SlugField(max_length=70, null=True, blank=True)
    text_standard_german = CKEditor5Field('Text', config_name='extends')
    text_chordpro = CKEditor5Field('Text', config_name='extends')
    text_chords = CKEditor5Field('Text', config_name='extends')
    text_nashville = CKEditor5Field('Text', config_name='extends')
    song = models.ForeignKey(Song, on_delete=models.CASCADE, default='')

    def __str__(self):
        return self.song.song_title

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = self.song.slug
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('songarchiv:text', args=[str(self.slug)])


class Album_song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE, default='')
    song = models.ForeignKey(Song, on_delete=models.CASCADE, default='')
    position = models.IntegerField(default='')

    def __str__(self):
        return ("%s %s %s %s" % (self.album.album_title, self.song.song_title, self.song.id, self.position))


class Content_text(models.Model):
    content_kurz = models.CharField(max_length=256, default='')
    content_lang = CKEditor5Field('Text', config_name='extends')

    def __str__(self):
        return self.content_kurz

heuser/songarchiv/forms.py
import datetime
from django import forms

#from ckeditor.widgets import CKEditorWidget
from django_ckeditor_5.widgets import CKEditor5Widget

from .models import Song, Album, Song_Text


class IndexForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'autofocus': 'autofocus',
            'placeholder': 'Titel eingeben ...'
        }
    ),
        required=False
    )


class SongForm(forms.ModelForm):
    song_title = forms.CharField(required=True,
                                 max_length=150,
                                 widget=forms.TextInput(
                                     attrs={
                                         'class': 'form-control',
                                         'autofocus': 'autofocus',
                                         'placeholder': 'Songtitel eingeben ...'
                                     }
                                 )
                                 )

    song_tag = forms.CharField(required=False,
                                 max_length=500,
                                 widget=forms.TextInput(
                                     attrs={
                                         'class': 'form-control',
                                         'autofocus': 'autofocus',
                                         'placeholder': 'Tags eingeben ...'
                                     }
                                 )
                                 )

    song_artist = forms.CharField(required=True,
                                  max_length=150,
                                  initial='Björn Heuser',
                                  widget=forms.TextInput(
                                      attrs={
                                          'class': 'form-control',
                                          'placeholder': 'Künstler eingeben ...'
                                      }
                                  )
                                  )

    song_music = forms.CharField(required=False,
                                 max_length=150,
                                 initial='Björn Heuser',
                                 widget=forms.TextInput(
                                     attrs={
                                         'class': 'form-control',
                                         'placeholder': 'Wer hat die Musik geschrieben?'
                                     }
                                 )
                                 )

    song_lyrics = forms.CharField(required=False,
                                  max_length=150,
                                  initial='Björn Heuser',
                                  widget=forms.TextInput(
                                      attrs={
                                          'class': 'form-control',
                                          'placeholder': 'Wer hat den Text geschrieben?'
                                      }
                                  )
                                  )

    song_year = forms.DateField(required=True,
                                initial='1900-01-01',
                                widget=forms.DateInput(
                                    attrs={
                                        'class': 'form-control',
                                        'placeholder': 'Erscheinungsjahr ...'
                                    }
                                )
                                )

    song_publisher = forms.CharField(required=False,
                                     max_length=150,
                                     initial='HEUSERMUSIK, GMO Publishing',
                                     widget=forms.TextInput(
                                         attrs={
                                             'class': 'form-control',
                                             'placeholder': 'Verlag ...'
                                         }
                                     )
                                     )

    song_producer = forms.CharField(required=False,
                                    max_length=150,
                                    widget=forms.TextInput(
                                        attrs={
                                            'class': 'form-control',
                                            'placeholder': 'Produzent ...'
                                        }
                                    )
                                    )

    song_spotify_iframe = forms.CharField(required=False,
                                   max_length=500,
                                   widget=forms.TextInput(
                                       attrs={
                                           'class': 'form-control',
                                           'placeholder': 'Link zu Spotify ...'
                                       }
                                   )
                                   )

    song_spotify = forms.CharField(required=False,
                                   max_length=150,
                                   widget=forms.TextInput(
                                       attrs={
                                           'class': 'form-control',
                                           'placeholder': 'Link zu Spotify ...'
                                       }
                                   )
                                   )

    song_amazon = forms.CharField(required=False,
                                  max_length=150,
                                  widget=forms.TextInput(
                                      attrs={
                                          'class': 'form-control',
                                          'placeholder': 'Link zu Amazon-Music ...'
                                      }
                                  )
                                  )

    song_itunes = forms.CharField(required=False,
                                  max_length=150,
                                  widget=forms.TextInput(
                                      attrs={
                                          'class': 'form-control',
                                          'placeholder': 'Link zu iTunes ...'
                                      }
                                  )
                                  )
#    song_snippet = forms.FileField()
#    song_snippet = forms.CharField(required=False,
#                                  max_length=150,
#                                  widget=forms.TextInput(
#                                      attrs={
#                                          'class': 'form-control',
#                                          'placeholder': 'Name Snippet Datei ...'
#                                      }
#                                  )
#                                  )

    song_cover = forms.CharField(required=False,
                                  max_length=150,
                                  widget=forms.TextInput(
                                      attrs={
                                          'class': 'form-control',
                                          'placeholder': 'Name der Cover-Datei ...'
                                      }
                                  )
                                  )

    song_youtube = forms.CharField(required=False,
                                  max_length=500,
                                  widget=forms.TextInput(
                                      attrs={
                                          'class': 'form-control',
                                          'placeholder': 'Link zu Youtube ...'
                                      }
                                  )
                                  )

    song_youtube_2 = forms.CharField(required=False,
                                  max_length=500,
                                  widget=forms.TextInput(
                                      attrs={
                                          'class': 'form-control',
                                          'placeholder': 'Link zu Youtube ...'
                                      }
                                  )
                                  )

    song_youtube_3 = forms.CharField(required=False,
                                  max_length=500,
                                  widget=forms.TextInput(
                                      attrs={
                                          'class': 'form-control',
                                          'placeholder': 'Link zu Youtube ...'
                                      }
                                  )
                                  )

    song_amazon_sale = forms.CharField(required=False,
                                  max_length=250,
                                  widget=forms.TextInput(
                                      attrs={
                                          'class': 'form-control',
                                          'placeholder': 'Link zum Amazon Shop ...'
                                      }
                                  )
                                  )

    song_background = forms.CharField(required=False,
                                      widget=forms.Textarea(
                                          attrs={
                                              'class': 'form-control',
                                              'placeholder': 'Hintergrund zum Song ...'
                                          }
                                      )
                                      )
    song_activ = forms.CheckboxInput(
                            )


    album = forms.ModelChoiceField(required=False, queryset=Album.objects.all().order_by('album_title'))

    class Meta:
        model = Song

heuser/songarchiv/templates/base.html
<!doctype html>
<html lang="de">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="keywords" content="Björn Heuser, Songarchiv, Kölsche Lieder, Köln">
    <meta name="subject" content="Björn Heuser Songarchiv">
    <meta name="description" content="Offizielles Songarchiv des Kölner Liedermachers Björn Heuser. Songtexte, Akkorde in
    verschiedenen Varianten, Links nach amazon music, Spotify und iTunes und vieles mehr im Songarchiv">
    <meta name="author" content="Norbert Krings, norbert.krings@gmail.com">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    {% load static %}

    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'favicon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'favicon/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'favicon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'favicon/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'favicon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'favicon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'favicon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'favicon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">

    {% if PRODUCTION == 'prod' %}
        {% load cookiebanner %}
    {% else %}
        <meta name="Entwicklung" content="Entwicklung">
    {% endif %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'songarchiv/songarchiv.css' %}">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    {% block extrahead %}{% endblock %}
    <title> {% block title %}Offizielles Song-Archiv des Liedermachers Björn Heuser{% endblock %}</title>

    {% if PRODUCTION == 'prod' %}
        {% cookie_accepted 'analytics' as cookie_analytics %}
        {% if cookie_analytics %}

<!-- Matomo -->
<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//apache4.xkgmbh.eu/matomo/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->


        {% endif %}
    {% else %}
    {% endif %}

</head>

<body>


    {% include "header.html" %}

{% block nav %}{% endblock %}

{% block content %}
    {% endblock %}
    {% if PRODUCTION == 'prod' %}
        {% cookiebanner_modal 'vanilla' %}
    {% else %}
    {% endif %}
{% include "footer.html" %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static 'songarchiv/js/jquery-ui-1.12.1.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>



<script>
  $( function() {
    $( "#id_title" ).autocomplete({
      source: '{% url 'songarchiv:autocomplete' %}',
      minLength: 2,
      select: function(event, ui) {
            $("#id_title").val(ui.item.value);
            $("#searchform").submit();
        }
    });
  });
</script>
<script>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
</script>

</body>
</html>

heuser/songarchiv/templates/footer.html
       <div class="footer" text-center header>
            <div class="row" >
                <div class="col-lg-4 d-none d-lg-block">
                    <div class="text-white">
                        <center><a class="text-white" href="https://t000bcaed.emailsys1a.net/190/4891/06f6652be4/subscribe/form.html">Newsletter-Anmeldung</a></center>
                    </div>
                </div>
                <div class="col-lg-4 d-none d-lg-block">
                    <div class="text-white">
                        <center><a class="text-white" href="{% url 'songarchiv:uebers-songarchiv'%}">Övver dat Songarchiv</a></center>
                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="text-white">
                        <center><a class="text-white" href="{% url 'songarchiv:impressum'%}">Impressum</a> / <a class="text-white" href="{% url 'songarchiv:datenschutz'%}">Datenschutzerklärung</a></center>
                    </div>
                </div>
            </div>
       </div>

heuser/songarchiv/templates/header.html
{% load static %}
<div class="container-fluid">
    <div class="row d-none d-lg-block">
        <img src="{% static 'songarchiv/images/header.jpg' %}" width='100%' height="180px" alt="Headerbild">
    </div>
</div>

heuser/songarchiv/templates/owa_script.html
{% cookie_accepted 'analytics' as cookie_analytics %}
{% if cookie_analytics %}
<script type="text/javascript">
    //<![CDATA[
    var owa_baseUrl = 'https://bheuser.uber.space/owa/';
    var owa_cmds = owa_cmds || [];
    owa_cmds.push(['setSiteId', '0dccd76f9521dd012aaa4dec5b581aea']);
    owa_cmds.push(['trackPageView']);
    owa_cmds.push(['trackClicks']);

    (function() {
        var _owa = document.createElement('script'); _owa.type = 'text/javascript'; _owa.async = true;
        owa_baseUrl = ('https:' == document.location.protocol ? window.owa_baseSecUrl || owa_baseUrl.replace(/http:/, 'https:') : owa_baseUrl );
        _owa.src = owa_baseUrl + 'modules/base/js/owa.tracker-combined-min.js';
        var _owa_s = document.getElementsByTagName('script')[0]; _owa_s.parentNode.insertBefore(_owa, _owa_s);
    }());
    //]]>
</script>
{% endif %}