heuser/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('bhcount/', views.BHCountListView.as_view(), name='bhcount'),
    path('bhtextcount/', views.BHTextCountListView.as_view(), name='bhtextcount'),
    path('text/', views.TextListView.as_view(), name='text'),
    path('chordpro/', views.ChordproListView.as_view(), name='chordpro'),
    path('chords/', views.ChordsListView.as_view(), name='chords'),
    path('nashville/', views.NashvilleListView.as_view(), name='nashville'),
    path('standard/', views.StandardListView.as_view(), name='standard'),
    path('publisher/', views.PublisherListView.as_view(), name='publisher'),
    path('producer/', views.ProducerListView.as_view(), name='producer'),
]

heuser/heuser/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView, TemplateView


urlpatterns = [
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path('', RedirectView.as_view(url='songarchiv/', permanent=True)),
    path('songarchiv/', include('songarchiv.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

# Dies ist nur für die Entwicklung notwendig. In Produktion braucht es einen Eintrag in der conf Datei von nginx
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path("ckeditor5/", include('django_ckeditor_5.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

heuser/songarchiv/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'songarchiv'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/song/', views.add_song, name='add_song'),
    path('search/song/', views.search_song, name='search_song'),
    path('edit/song/<id>/', views.edit_song, name='edit_song'),
    path('song/<slug:slug>/', views.song, name='song'),
    path('del/song/<pk>', views.del_song.as_view(), name='del_song'),
    path('song_delete_done', views.song_delete_done, name='del_song_done'),
    path('autocomplete', views.autocomplete, name='autocomplete'),

    path('add/album/', views.add_album, name='add_album'),
    path('search/album/start', views.search_album_start, name='search_album_start'),
    path('search/album/', views.search_album, name='search_album'),
    path('edit/album/<id>/', views.edit_album, name='edit_album'),
    path('album/', views.album, name='album'),
    path('single/', views.single, name='single'),

    path('add/text/', views.add_text, name='add_text'),
    path('edit/text/<id>/', views.edit_text, name='edit_text'),
    path('text/<slug:slug>/', views.text, name='text'),

    path('print_text/', views.print_text, name='print_text'),
    path('print_chordpro/', views.print_chordpro, name='print_chordpro'),
    path('print_chords/', views.print_chords, name='print_chords'),
    path('print_nashville/', views.print_nashville, name='print_nashville'),

    path('videostaendchen/', views.videostaendchen, name= 'videostaendchen'),
    path('staendchenlist/', views.staendchenlist, name='staendchenlist'),

    path('cd_song_list/<id>/', views.cd_song_list, name='cd_song_list'),

    path('impressum/', views.impressum, name='impressum'),
    path('datenschutz/', views.datenschutz, name='datenschutz'),
    path('uebers_songarchiv/', views.uebers_songarchiv, name='uebers-songarchiv'),


]

heuser/songarchiv/models.py
from django.db import models
#from ckeditor.fields import RichTextField
from django_ckeditor_5.fields import CKEditor5Field
from django.urls import reverse
from django.utils.text import slugify

# diese Funktion kann ggf. weg, da sie in songs bei den snipplet eingesetzt war, aber eigentlich nicht benötigt wird
def dynamik_path(instance, filename):
    file_path = '{filename}'.format(filename=filename)
    return file_path


class Album(models.Model):

    ALBUM_SINGLE = (
        ('1', 'Album'),
        ('2', 'Single'),
        ('2', 'LDÖS'),
        ('2', 'Sonstiges'),
    )

    album_title = models.CharField(max_length=250)
    album_year = models.DateField(default='1900-01-01')
    album_cover_image = models.ImageField(upload_to='cover/', null=True, blank=True)
    album_spotify = models.CharField(max_length=500, default='')
    album_amazon_selling = models.CharField(max_length=1000, default='')
    album_single = models.CharField(max_length=20, choices=ALBUM_SINGLE, default='1')

    def __str__(self):
        return self.album_title


class Song(models.Model):
    song_title = models.CharField(max_length=250, unique=True)
    song_tag = models.CharField(max_length=500, blank=True, default="")
    slug = models.SlugField(max_length=70, null=True, blank=True)
    song_artist = models.CharField(max_length=250)
    song_music = models.CharField(max_length=250, blank=True, default='')
    song_lyrics = models.CharField(max_length=250, blank=True, default='')
    song_year = models.DateField(blank=True, default='1900-01-01')
    song_publisher = models.CharField(max_length=250, blank=True, default='')
    song_producer = models.CharField(max_length=125, blank=True, default='')
    song_spotify_iframe = models.CharField(max_length=500, blank=True, default='')
    song_spotify = models.URLField(max_length=250, blank=True, default='')
    song_amazon = models.URLField(max_length=250, blank=True, default='')
    song_itunes = models.URLField(max_length=250, blank=True, default='')
    song_snippet = models.FileField(upload_to='mp3/', max_length=100, blank=True)
    song_youtube = models.CharField(max_length=500, blank=True, default='')
    song_youtube_2 = models.CharField(max_length=500, blank=True, default='')
    song_youtube_3 = models.CharField(max_length=500, blank=True, default='')
    song_amazon_sale = models.CharField(max_length=250, blank=True, default='')
    song_background = models.TextField(blank=True, default='')
    song_activ = models.BooleanField(default=True)
    album = models.ForeignKey(Album, on_delete=models.PROTECT, blank=True, null=True)

    def __str__(self):
        return self.song_title

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            german_title = self.song_title.lower()
            german_title = (german_title.translate(str.maketrans({'ä': 'ae', 'ö': 'oe', 'ü': 'ue', 'ß': 'ss'})))
            german_title = 'bjoern-heuser-' + german_title
            self.slug = slugify(german_title)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        #return "/songarchiv/song/%s/" % self.slug
        return reverse('songarchiv:song', args=[str(self.slug)])
        #return reverse('songarchiv:song', kwargs={'id': self.id, 'slug': self.slug })


    class Meta:
        ordering = ['album__album_title']


class Song_Text(models.Model):
    text_text = CKEditor5Field('Text', config_name='extends')
    slug = models.SlugField(max_length=70, null=True, blank=True)
    text_standard_german = CKEditor5Field('Text', config_name='extends')
    text_chordpro = CKEditor5Field('Text', config_name='extends')
    text_chords = CKEditor5Field('Text', config_name='extends')
    text_nashville = CKEditor5Field('Text', config_name='extends')
    song = models.ForeignKey(Song, on_delete=models.CASCADE, default='')

    def __str__(self):
        return self.song.song_title

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = self.song.slug
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('songarchiv:text', args=[str(self.slug)])


class Album_song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE, default='')
    song = models.ForeignKey(Song, on_delete=models.CASCADE, default='')
    position = models.IntegerField(default='')

    def __str__(self):
        return ("%s %s %s %s" % (self.album.album_title, self.song.song_title, self.song.id, self.position))


class Content_text(models.Model):
    content_kurz = models.CharField(max_length=256, default='')
    content_lang = CKEditor5Field('Text', config_name='extends')

    def __str__(self):
        return self.content_kurz

heuser/songarchiv/templates/songarchiv/album.html
{% extends "base.html" %}

{% block extrahead %}
    {% load static %}
{% endblock %}

{% block title %}
    Heuser Songarchiv - Alben
{% endblock %}

{% block nav %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a href="{% url 'songarchiv:index' %}" class="navbar-brand">Song suchen</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar6">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse justify-content-stretch" id="navbar6">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'songarchiv:single' %}">Singles</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="https://heuser-koeln.de" target="_blank">Heuser Homepage</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="https://heuserkoeln.de" target="_blank">Heuser Shop</a>
            </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
            </li>
        {% endif %}
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'logout'%}"><i class="fa fa-sign-out" style="font-size:24px"></i> Logout</a>
            {% else %}
                <a class="nav-link" href="{% url 'login'%}"><i class="fa fa-sign-in" style="font-size:24px"></i> Login</a>
            {% endif %}
            </li>
        </ul>
    </div>
</nav>
{% endblock %}

{% block content %}
<content>
    <p></p>
    <div class="container-fluid">
        <div class="row justify-content-center d-flex">
            <h1>Heuser Alben</h1>
        </div>

        {% for alb in album %}
          <div class="row">
            <div class="col-md-2">&nbsp;</div>
            <div class="col-md-3 pt-3">
                <a href="{% url 'songarchiv:cd_song_list' alb.id %}" target="_top" data-toggle='tooltip' data-placement='left' title='zur Songliste'>
                    <img class="img-fluid" src="{{ alb.album_cover_image.url }}" width="500"
                         alt="Coverbild {{ alb.album_title }}"
                         title="Album: {{ alb.album_title }}"
                    >
                </a>
            </div>
            <div class="col-md-3 pt-3 justify-content-center d-flex">
                <div class="row align-self-center"> {{ alb.album_spotify | safe}} </div>
                {% if alb.album_amazon_selling %}
            </div>
            <div class="col-md-2 pt-3 justify-content-center d-flex">
                <div class="row align-self-center">
                    <a href="{{ alb.album_amazon_selling }}" target="_blank">
                            <img class="img-fluid" src="{% static 'songarchiv/images/'%}amazon_shop2.png"
                                 width="200"
                                 alt="amazon Sales Logo"
                                 title="Direkt zu amazon Sale"
                            >
                    </a>
                </div>
                {% endif %}
            </div>
          <div class="col-md-2 pt-3 justify-content-center d-flex">
                {% if user.is_authenticated %}
                <div class="row  align-self-center">
                    <a class="nav-link" href="{% url 'songarchiv:edit_album' alb.id %}"><i class="fa fa-pencil fa-fw text-dark" style="font-size:24px"></i></a>
                </div>
                {% endif %}
          </div>
          </div>
        <div class="row">
            &nbsp;
        </div>
      {% endfor %}
   </div>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
</content>
{% endblock %}

heuser/songarchiv/templates/songarchiv/single.html
{% extends "base.html" %}

{% block extrahead %}
{% load static %}
{% endblock %}

{% block title %}
    Heuser Songarchiv - Singles
{% endblock %}


{% block nav %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a href="{% url 'songarchiv:index' %}" class="navbar-brand">Song suchen</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar6">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse justify-content-stretch" id="navbar6">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'songarchiv:album' %}">Alben</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="https://heuser-koeln.de" target="_blank">Heuser Homepage</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="https://heuserkoeln.de" target="_blank">Heuser Shop</a>
            </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
            </li>
        {% endif %}
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'logout'%}"><i class="fa fa-sign-out" style="font-size:24px"></i> Logout</a>
            {% else %}
                <a class="nav-link" href="{% url 'login'%}"><i class="fa fa-sign-in" style="font-size:24px"></i> Login</a>
            {% endif %}
            </li>
        </ul>
    </div>
</nav>
{% endblock %}

{% block content %}
<content>
    <p></p>
    <div class="container-fluid">
        <div class="row justify-content-center d-flex">
            <h1>Heuser Singles</h1>
        </div>

        {% for alb in album %}
          <div class="row">
            <div class="col-sm-2">&nbsp;</div>
            <div class="col-sm-4 pt-3">
                <a href="{{ alb.album_amazon_selling}}" target="_blank" data-toggle='tooltip' data-placement='left' title='zur Bestellung'>
                    <img class="img-fluid" src="{{ alb.album_cover_image.url }}"
                         width="500"
                         alt="Coverbild {{ alb.album_title }}"
                         title="Album: {{ alb.album_title }}"
                    >
                </a>
            </div>
            <div class="col-sm-5 pt-3 justify-content-center d-flex">
                <div class="row  align-self-center"> {{ alb.album_spotify | safe}} </div>
            </div>
            <div class="col-sm-1 pt-3 justify-content-center d-flex">
                {% if user.is_authenticated %}
                <div class="row  align-self-center">
                    <a class="nav-link" href="{% url 'songarchiv:edit_album' alb.id %}"><i class="fa fa-pencil fa-fw text-dark" style="font-size:24px"></i></a>
                </div>
                {% endif %}
            </div>
          </div>
        <div class="row">
            &nbsp;
        </div>
      {% endfor %}
   </div>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
</content>
{% endblock %}

heuser/songarchiv/templates/songarchiv/text.html
{% extends "base.html" %}

{% block extrahead %}
{% load static %}
{% endblock %}

{% block title %}
    Heuser Songarchiv - {{ song.song_title }}
{% endblock %}

{% block nav %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a href="{% url 'songarchiv:index' %}" class="navbar-brand">Song suchen</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar6">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse justify-content-stretch" id="navbar6">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <!--
                <a class="nav-link" href="{% url 'songarchiv:song' text.song_id %}">zurück</a>
                -->
                <a class="nav-link" href="{{ song.get_absolute_url }}">zurück</a>

            </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'songarchiv:edit_text' text.id %}">Song-Text ändern</a>
            </li>
        {% endif %}
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'logout'%}"><i class="fa fa-sign-out" style="font-size:24px"></i> Logout</a>
            {% else %}
                <a class="nav-link" href="{% url 'login'%}"><i class="fa fa-sign-in" style="font-size:24px"></i> Login</a>
            {% endif %}
            </li>
        </ul>
    </div>
</nav>
{% endblock %}

{% block content %}
<content>
    <p></p>
    {% if user_agent == 'mobile' %}
    <div class="container-fluid">
    {% else %}
    <div class="container">
    {% endif %}
          <div class="row">
              <div class="col-sm-2">
                  <div class="inline"></div>
              </div>
              <div class="col-sm-4">

              </div>
          </div>
        <div class="col">
             <ul class="nav nav-tabs" id="myTab" role="tablist">
              <li class="nav-item">
                    <a class="nav-link text-dark" id="text-tab" data-toggle="tab" href="#text" role="tab" aria-controls="text" aria-selected="false">Text</a>
              </li>
              {% if text.text_standard_german%}
              <li class="nav-item">
                    <a class="nav-link  text-dark" id="text-german-tab" data-toggle="tab" href="#text-german" role="tab" aria-controls="text-german" aria-selected="false">Hochdeutsch</a>
              </li>
              {% endif %}
              {% if text.text_chordpro%}
              <li class="nav-item">
                    <a class="nav-link text-dark" id="chordpro-tab" data-toggle="tab" href="#chordpro" role="tab" aria-controls="chordpro" aria-selected="false">Chordpro</a>
              </li>
              {% endif %}
              {% if text.text_chords%}
              <li class="nav-item">
                    <a class="nav-link text-dark active" id="chords-tab" data-toggle="tab" href="#chords" role="tab" aria-controls="chords" aria-selected="false">Chords</a>
              </li>
              {% endif %}
              {% if text.text_nashville%}
              <li class="nav-item">
                    <a class="nav-link text-dark" id="nashville-tab" data-toggle="tab" href="#nashville" role="tab" aria-controls="nashville" aria-selected="false">Nashville-Style</a>
              </li>
              {% endif %}
              <li class="nav-item">
                    <a class="nav-link text-dark" id="download-tab" data-toggle="tab" href="#download" role="tab" aria-controls="download" aria-selected="false">Downloads</a>
              </li>
             </ul>
            <div class="tab-content" id="myTabContent">

                  <div class="tab-pane fade" id="text" role="tabpanel" aria-labelledby="text-tab">
                      <div class="row bg-white">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-9"><h3>{{ song.song_title }}</h3></div>
                      </div>
                      <div class="row bg-white">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-11 small">
                            {% if song.song_music == song.song_lyrics %}
                              Musik & Text {{ song.song_music }} / Verlag: {{ song.song_publisher }}
                            {% else %}
                              Musik: {{ song.song_music }}; Text: {{ song.song_lyrics }} / Verlag: {{ song.song_publisher }}
                            {% endif %}
                          </div>
                      </div>
                      <div class="row bg-white">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-11">&nbsp;</div>
                      </div>
                      <div class="row bg-white ">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-11">{{ text.text_text| safe }}</div>
                      </div>
                  </div>

                  <div class="tab-pane fade" id="text-german" role="tabpanel" aria-labelledby="text-german-tab">
                      <div class="row bg-white">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-9"><h3>{{ song.song_title }}</h3></div>
                      </div>
                      <div class="row bg-white">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-11 small">
                            {% if song.song_music == song.song_lyrics %}
                              Musik & Text {{ song.song_music }} / Verlag: {{ song.song_publisher }}
                            {% else %}
                              Musik: {{ song.song_music }}; Text: {{ song.song_lyrics }} / Verlag: {{ song.song_publisher }}
                            {% endif %}
                          </div>
                      </div>
                      <div class="row bg-white">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-11">&nbsp;</div>
                      </div>
                      <div class="row bg-white ">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-11">{{ text.text_standard_german| safe }}</div>
                      </div>

                  </div>

                  <div class="tab-pane fade" id="chordpro" role="tabpanel" aria-labelledby="chordpro-tab">
                      <div class="row bg-white">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-9"><h3>{{ song.song_title }}</h3></div>
                      </div>
                      <div class="row bg-white">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-11 small">
                            {% if song.song_music == song.song_lyrics %}
                              Musik & Text {{ song.song_music }} / Verlag: {{ song.song_publisher }}
                            {% else %}
                              Musik: {{ song.song_music }}; Text: {{ song.song_lyrics }} / Verlag: {{ song.song_publisher }}
                            {% endif %}
                          </div>
                      </div>
                      <div class="row bg-white">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-11">&nbsp;</div>
                      </div>
                      <div class="row bg-white ">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-11">{{ text.text_chordpro| safe }}</div>
                      </div>
                  </div>

                  <div class="tab-pane fade show active" id="chords" role="tabpanel" aria-labelledby="chords-tab">
                      <div class="row bg-white">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-9"><h3>{{ song.song_title }}</h3></div>
                      </div>
                      <div class="row bg-white">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-11 small">
                            {% if song.song_music == song.song_lyrics %}
                              Musik & Text {{ song.song_music }} / Verlag: {{ song.song_publisher }}
                            {% else %}
                              Musik: {{ song.song_music }}; Text: {{ song.song_lyrics }} / Verlag: {{ song.song_publisher }}
                            {% endif %}
                          </div>
                      </div>
                      <div class="row bg-white">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-11">&nbsp;</div>
                      </div>
                      <div class="row bg-white ">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-11">{{ text.text_chords| safe }}</div>
                      </div>
                  </div>

                 <div class="tab-pane fade" id="nashville" role="tabpanel" aria-labelledby="nashville-tab">
                      <div class="row bg-white">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-9"><h3>{{ song.song_title }}</h3></div>
                      </div>
                      <div class="row bg-white">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-11 small">
                            {% if song.song_music == song.song_lyrics %}
                              Musik & Text {{ song.song_music }} / Verlag: {{ song.song_publisher }}
                            {% else %}
                              Musik: {{ song.song_music }}; Text: {{ song.song_lyrics }} / Verlag: {{ song.song_publisher }}
                            {% endif %}
                          </div>
                      </div>
                      <div class="row bg-white">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-11">&nbsp;</div>
                      </div>
                      <div class="row bg-white ">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-11">{{ text.text_nashville| safe }}</div>
                      </div>
                  </div>

                  <div class="tab-pane fade" id="download" role="tabpanel" aria-labelledby="download-tab">
                      <div class="row bg-white">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-9"><h3>Download von "{{ song.song_title }}" als:</h3></div>
                      </div>
                      <div class="row bg-white">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-11">
                              <a href="{% url 'songarchiv:print_text' %}?slug={{text.slug}}">
                                  <button type="button" class="btn btn-dark">Nur den Text</button>
                              </a>
                          </div>
                      </div>
                  {% if text.text_chords %}
                      <div class="row bg-white">&nbsp;</div>
                      <div class="row bg-white">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-11">
                            <a href="{% url 'songarchiv:print_chords' %}?slug={{text.slug}}">
                              <button type="button" class="btn btn-dark">Text und Akkorde</button>
                            </a>
                          </div>
                      </div>
                  {% endif %}
                  {% if text.text_chordpro %}
                      <div class="row bg-white">&nbsp;</div>
                      <div class="row bg-white">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-11">
                            <a href="{% url 'songarchiv:print_chordpro' %}?slug={{text.slug}}">
                              <button type="button" class="btn btn-dark">Text und Akkorde {Chordpro}</button>
                            </a>
                          </div>
                      </div>
                  {% endif %}
                  {% if text.text_nashville %}
                      <div class="row bg-white">&nbsp;</div>
                      <div class="row bg-white ">
                          <div class="col-sm-1"></div>
                          <div class="col-sm-11">
                              <a href="{% url 'songarchiv:print_nashville' %}?slug={{text.slug}}">
                                  <button type="button" class="btn btn-dark">Text und Akkorde im Nashville-Style</button>
                              </a>
                          </div>
                      </div>
                  {% endif %}
                  </div>

              </div>
        </div>
    </div>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
</content>
{% endblock %}

heuser/songarchiv/templates/songarchiv/videostaendchenliste.html
{% extends "base.html" %}

{% block extrahead %}
{% load static %}
{% endblock %}

{% block title %}
    Heuser Songarchiv - Songliste für Videoständchen
{% endblock %}

{% block nav %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a href="{% url 'songarchiv:index' %}" class="navbar-brand">Song suchen</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar6">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse justify-content-stretch" id="navbar6">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'songarchiv:videostaendchen' %}">zurück</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'logout'%}"><i class="fa fa-sign-out" style="font-size:24px"></i> Logout</a>
            {% else %}
                <a class="nav-link" href="{% url 'login'%}"><i class="fa fa-sign-in" style="font-size:24px"></i> Login</a>
            {% endif %}
            </li>
        </ul>
    </div>
</nav>
{% endblock %}

{% block content %}
<content>
    <p></p>
    <div class="container container_extend">
        <div class="row">
            <div class="col">
                <center><h3>Songs der Kategorie "{{kategorie}}".</h3></center>
                <center><h4>Bestimmt findest du anhand des Texts und des Song-Snipplets den perfekten Song für dein persönliches Videoständchen von Björn Heuser.</h4></center>
            </div>
        </div>
        <br>
        {% for song in song_list %}
            <div class="row">
                <div class="col-md-1">&nbsp;</div>
                <div class="col-md-6">
                    {% if forloop.first %}
                    <details open>
                    {% else %}
                    <details>
                    {% endif %}
                        <summary class="font-weight-bolder lead">{{song.song.song_title}}</summary>
                        <p></p>
                        {{song.text_text | safe}}
                    </details>
                </div>
                <div class="col-md-3">
                    {{ song.song.song_spotify_iframe| safe}}<br>
                    <a class="text-primary font-weight-bolder lead" href="https://www.heuserkoeln.de/shop-1" target="_blank"> --> zum Heuser-Shop...</a>
                </div>
                <div class="col-md-1">&nbsp;</div>
            </div>
            <div class="row">
                &nbsp;
            </div>
        {% endfor %}
   </div>
</content>
{% endblock %}